development:
  adapter: redis
  connection: redis://localhost:6379/4
test:
  collecting: false
production:
  adapter: redis
  connection: redis://<%= ENV["REDIS_USER"] %>:<%= ENV["REDIS_PASSWORD"] %>@<%= ENV["REDIS_HOST"] %>:<%= ENV["REDIS_PORT"] %>/0
